apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}
spec:
  refreshInterval: {{ .Values.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: {{ .Release.Name }}
    creationPolicy: {{ .Values.target.creationPolicy }}
    deletionPolicy: {{ .Values.target.deletionPolicy }}
  dataFrom:
    - extract:
        key: {{ printf "%s/%s/%s" .Values.vault.kvMount .Values.vault.prefix .Release.Name }}
