# Generated by patternizer
# This Makefile includes the common pattern targets from Makefile-common
# You can add custom targets above or below the include line

include Makefile-common

# Initialize fresh Vault installations before the utility's late secret loader
# waits for an unsealed Vault and its hub auth policy.
INSTALL_PLAYBOOK := ansible/playbooks/install.yaml
LOAD_SECRETS_PLAYBOOK := ansible/playbooks/load-secrets.yaml

# Default matches main.variant in values-global.yaml: one four-L4 AWS worker.
# PROFILE=bf16 exports TARGET_VARIANT so the utility container installs that variant.
PROFILE ?= bf16-tp4

ifneq ($(PROFILE),)
ifeq ($(wildcard variants/$(PROFILE)/values-$(PROFILE).yaml),)
$(error Unknown PROFILE '$(PROFILE)'. Expected variants/$(PROFILE)/values-$(PROFILE).yaml)
endif
ifeq ($(wildcard profiles/$(PROFILE).yaml),)
$(error Unknown PROFILE '$(PROFILE)'. Expected profiles/$(PROFILE).yaml)
endif
ifneq ($(shell grep -c '^placeholder:' profiles/$(PROFILE).yaml),0)
$(error PROFILE=$(PROFILE) is a placeholder and cannot be installed)
endif
export TARGET_VARIANT := $(PROFILE)
include profiles/$(PROFILE).mk
endif

# Phase 0 fallback values for single-GPU profiles; the selected .mk overrides these.
GPU_SKU_REQUIREMENT ?= an 80 GiB GPU SKU
ifneq ($(GPU_INSTANCE_TYPE_REQUIRED),true)
GPU_INSTANCE_TYPE ?= g6.2xlarge
endif
GPU_REPLICAS ?= 1
GPU_COUNT ?= 1
GPU_MEMORY_MB ?= 32768
GPU_VCPU ?= 8
GPU_ROOT_VOLUME_SIZE ?= 150
# Azure playbook defaults to 2 replicas (rag-llm-gitops); override when you need a single worker.
GPU_REPLICAS_AZURE ?= 2
ifneq ($(GPU_VM_SIZE_REQUIRED),true)
GPU_VM_SIZE ?= Standard_NC8as_T4_v3
endif
OVERRIDE_ZONE ?=

.PHONY: ensure-pattern-namespaces
ensure-pattern-namespaces: ## Create aiq and aiq-inference namespaces and RHOAI labels before install
	oc create namespace aiq --dry-run=client -o yaml | oc apply -f -
	oc create namespace aiq-inference --dry-run=client -o yaml | oc apply -f -
	oc label namespace aiq-inference opendatahub.io/dashboard=true modelmesh-enabled=false --overwrite

.PHONY: check-gpu-instance-type
check-gpu-instance-type:
	@if [ "$(GPU_INSTANCE_TYPE_REQUIRED)" = true ] && [ -z "$(GPU_INSTANCE_TYPE)" ]; then \
		echo "PROFILE=$(PROFILE) requires GPU_INSTANCE_TYPE set to $(GPU_SKU_REQUIREMENT)" >&2; \
		exit 1; \
	fi

.PHONY: check-gpu-vm-size
check-gpu-vm-size:
	@if [ "$(GPU_VM_SIZE_REQUIRED)" = true ] && [ -z "$(GPU_VM_SIZE)" ]; then \
		echo "PROFILE=$(PROFILE) requires GPU_VM_SIZE set to $(GPU_SKU_REQUIREMENT)" >&2; \
		exit 1; \
	fi

.PHONY: create-gpu-machineset
create-gpu-machineset: check-gpu-instance-type ## Create AWS GPU MachineSet (overrides: GPU_INSTANCE_TYPE, GPU_REPLICAS, OVERRIDE_ZONE, PROFILE)
	ansible-playbook ansible/playbooks/create-gpu-machineset.yaml \
		-e "gpu_instance_type=$(GPU_INSTANCE_TYPE) gpu_replicas=$(GPU_REPLICAS) override_zone=$(OVERRIDE_ZONE) gpu_count=$(GPU_COUNT) gpu_memory_mb=$(GPU_MEMORY_MB) gpu_vcpu=$(GPU_VCPU) gpu_root_volume_size=$(GPU_ROOT_VOLUME_SIZE)"

.PHONY: create-gpu-machineset-azure
create-gpu-machineset-azure: check-gpu-vm-size ## Create Azure GPU MachineSet (overrides: GPU_VM_SIZE, GPU_REPLICAS_AZURE, OVERRIDE_ZONE, PROFILE)
	ansible-playbook ansible/playbooks/create-gpu-machineset-azure.yaml \
		-e "gpu_vm_size=$(GPU_VM_SIZE) gpu_replicas=$(GPU_REPLICAS_AZURE) override_zone=$(OVERRIDE_ZONE)"

# Ensure workload namespaces exist so RHOAI labels are present before wave 15.
pattern-install: ensure-pattern-namespaces
