apiVersion: datasciencecluster.opendatahub.io/v1
kind: DataScienceCluster
metadata:
  name: default-dsc
  annotations:
    argocd.argoproj.io/sync-wave: "15"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  components:
    dashboard:
      managementState: Removed
    workbenches:
      managementState: Removed
    datasciencepipelines:
      managementState: Removed
    kueue:
      managementState: Removed
    ray:
      managementState: Removed
    kserve:
      managementState: Managed
      rawDeploymentServiceConfig: Headed
