{{- if .Values.imagePullSecrets }}
{{- if .Values.imagePullSecrets.dockerRegistry }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.project.name }}-docker-pull-secret
  namespace: {{ include "aiq.namespace" . }}
  labels:
    {{- include "aiq.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.imagePullSecrets.dockerRegistry | b64enc }}
{{- end }}

{{- if .Values.imagePullSecrets.artifactRegistry }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.project.name }}-artifact-pull-secret
  namespace: {{ include "aiq.namespace" . }}
  labels:
    {{- include "aiq.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.imagePullSecrets.artifactRegistry | b64enc }}
{{- end }}
{{- end }}
