apiVersion: v2
name: aiq2-web
description: AI-Q - WEB Profile ()
type: application
version: 2.2.1
appVersion: '2.2.1'
dependencies:
- name: aiq
  version: 0.0.6
  repository: file://./helm-charts-k8s/aiq
  alias: aiq
