apiVersion: v2
name: aiq2-web
description: AI-Q - WEB Profile ()
type: application
version: 2.2.0
appVersion: '2.2.0'
dependencies:
- name: aiq
  version: 0.0.5
  repository: file://./helm-charts-k8s/aiq
  alias: aiq
