# SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
# Stubs for standalone helm template; Validated Patterns may override global.clusterVersion at deploy time.
global:
  clusterVersion: "4.16"
