# SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
# Stubs so `helm template` works standalone; Validated Patterns injects global.* at deploy time.
global: {}
clusterGroup: {}
