{{- if .Values.modelCache.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "vllm-inference-service.fullname" . }}-model-cache
  annotations:
    argocd.argoproj.io/sync-wave: "20"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.modelCache.size }}
  {{- with .Values.global.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
{{- end }}
